### ISSUE TITLE
Unable to determine the log caller in flutter web release/profile mode

### ISSUE THREAD

**Issue by motucraft** [mono0926/simple_logger#10]
Thank you for the informative package.

I don't think it is a simple_logger issue, but when I run Flutter Web in Profile mode, I can't identify the part of the source that is outputting the logs.

In debug mode, the source can be identified without problems.
Is this because I can't get a stack trace in Profile mode?

```
flutter run -d chrome --profile
```

![image](https://user-images.githubusercontent.com/35750184/212032937-012084ec-3945-4026-b313-d907d60b9b82.png)

```dart
import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart';
import 'package:simple_logger/simple_logger.dart';

final logger = SimpleLogger()
  ..setLevel(
    kReleaseMode ? Level.OFF : Level.ALL,
    includeCallerInfo: !kReleaseMode,
  );

void main() {
  logger.severe('severe');

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    logger.info('info');

    return const MaterialApp(
      title: 'Flutter Demo',
      home: Scaffold(),
    );
  }
}

```

**Comment by mono0926** [comment]
I think [current property - StackTrace class - dart:core library - Dart API](https://api.dart.dev/stable/2.18.7/dart-core/StackTrace/current.html) doesn't work properly on release/profile mode web, and there seems to be no way to address this on the package side.

**Comment by motucraft** [comment]
@mono0926 
Thanks for your response.

There is nothing like "--debug" option for "flutter build web", is there?
Therefore, I understood that the use case of "flutter build web" would not be able to identify the output source.

If I am wrong,  would help me if you corrected my understandings.

**Comment by motucraft** [comment]
Close because it is not a simple_logger issue.
